---
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Enabled: true
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'rakelib/**/*'

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'lib/itax_code/utils.rb'
    - 'test/**/*'

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ['array', 'hash']

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
...
