---
require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Enabled: true
  Max: 80

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ['array', 'hash']

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
...
